### ISSUE TITLE
Only the first cookie is considered

### ISSUE THREAD

**Issue by dasloop** [vinipsmaker/tufao#81]
A browser has more than one cookie but only the first is considered in:
QByteArray SessionStore::session(const HttpServerRequest &request) const

Because QNetworkCookie::parseCookies looks for cookies separated by a new line character but they are not.

Printing headers[i].constData() shows several cookies separated by spaces.

Thanks in advance

**Comment by vinipsmaker** [comment]
Issue confirmed. Thanks for the report. Gonna fix it in the next minutes.
