### ISSUE TITLE
doc: ldconfig after install

### ISSUE THREAD

**Issue by giraldeau** [vinipsmaker/tufao#82]
Compiling and linking my program with tufao worked, but I couldn't run it:
```
error while loading shared libraries: libtufao1.so.1: cannot open shared object file: No such file or directory
```
Indeed on Linux, it is required to run `sudo ldconfig` to update the dynamic library loader cache. Maybe it could be added to the installation doc?

BTW, thanks for this library, it's awesome!

**Comment by vinipsmaker** [comment]
> Maybe it could be added to the installation doc?

Sure. I'll add to the `README` file. Reopen the issue if you think this is not enough.

> BTW, thanks for this library, it's awesome!

You're welcome.
