### ISSUE TITLE
incoming urls with # i.e http://localhost/#index.html

### ISSUE THREAD

**Issue by jkayrouz** [vinipsmaker/tufao#98]
The # sign omits the entire URL from the incoming HTTPServerRequest.  I am unable to retrieve anything before t he # sign.  Is there a workaround?  I'm using the above url as an example.

**Comment by vinipsmaker** [comment]
Can you describe your problem in more detail?

**Comment by jkayrouz** [comment]
So, I eventually pursued another route.  But, the problem I was experiencing is this.  I was authenticating Twitch with OAuth.  So, I would send a request to twitch, they would then prompt the user of my application to redirect to http://localhost:8080/#blahblahblah?access_token=XXXXX

So, when I received that OnRequestReady(request, response) with that URL, I would check the request's URL, and it was blank.  I think anything after the "#" is ignored?  I hope this helps.  But, when I received a request to http://localhost:8080/blahblahblah?access_token=XXXXX  (note, the # is not there), then everything worked fine and I was able to see all the parameters and the URL from the request.

**Comment by vinipsmaker** [comment]
> I would check the request's URL, and it was blank. I think anything after the "#" is ignored?

Yup. Browser doesn't send anything that comes after the `#` sign. That's standard behaviour. That's — for instance — how mega managed to throw content responsibility on user behalf and escape anti-piracy laws.

**Comment by jkayrouz** [comment]
Thanks! I love your library by the way. Thank you.
